on: push

jobs:
  #Unit test
  test:
    timeout-minutes: 5
    runs-on: ubuntu-18.04
    steps:
    - name: Install JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
        java-package: jdk
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Run tests
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        # Gradle command line arguments, see gradle --help
        arguments: test
        # Caching for gradle stuff
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        
  
  #Jar creation
  jar:
    needs: [test]
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-18.04
    steps:
    - name: Install JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13
        java-package: jdk
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Cache dependancies
      uses: actions/cache@v2
      with:
        path: |
          ./gradle
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    - name: Create Jar
      run: |
        ./gradlew shadowJar
        
    - name: Upload JAR
      uses: actions/upload-artifact@v1
      with:
        name: shadowJar
        path: ./build/libs/gitnarwhal.jar
